#!/usr/bin/env python
import os
import sys
root_path = os.path.abspath(__file__)
#print("%s"%root_path)
root_path = '\\'.join(root_path.split('\\')[:-1])
sys.path.append(root_path)
#print("%s"%root_path)
import llvmbuild

if __name__ == '__main__':
   llvmbuild.main()
